// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using System.Reflection;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Anular
{

    [Obfuscation(Feature = "trigger", Exclude = false)]
    public class AnularDireccionamiento
    {

        [JsonProperty("Message")]
        public string Message { get; set; }

        [JsonProperty("Errors")]
        public IList<string> Errors { get; set; }

        [JsonProperty("Mensaje")]
        public string Mensaje { get; set; }
    }

}
